### ISSUE TITLE
posthog.project_api_key doesn't work

### ISSUE THREAD

**Issue by FreakyDug** [PostHog/posthog-python#31]
According to the docs (https://posthog.com/docs/libraries/python#installation) `posthog.api_key` has been deprecated in favour of `posthog.project_api_key`.

However, when I use `project_api_key` with the current version, 1.3.1, it does not work, while `api_key` does.

**Comment by yakkomajuri** [comment]
Hey! Are you by any chance passing both of them? Or do you have only `project_api_key` and it still doesn't work?

**Comment by neilkakkar** [comment]
Just tried this out, just `project_api_key` doesn't work either, and when both are set, we still give precedence to `api_key`. Thanks for pointing this out, @FreakyDug , will fix!

**Comment by FreakyDug** [comment]
Yeah, I was only setting `project_api_key`. Thanks for the quick response!

**Comment by Twixes** [comment]
This may be because actually in most places we still left `api_key`. `__init__.py` being one example. To fully deprecate `api_key` we need to change all of its occurrences to `project_api_key` (danger: this will be a user-facing API change unless we go to pretty extreme lengths to maintain the same getter/setter behavior for `project_api_key` and `api_key` everywhere).

**Comment by Twixes** [comment]
Alright, so we've released a [new version of the library](https://github.com/PostHog/posthog-python/releases/tag/1.4.0), which should work as expected here. Please give it a try @FreakyDug!

**Comment by FreakyDug** [comment]
That fixed it, thanks @Twixes! Very fast work!
